name: Check the barnch
on: [push]

jobs:
    branch_name:
        if : github.ref_name == 'main'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Branch name
              run: echo "The branch is ${{github.ref_name}}"
    deploy:
        needs: branch_name
        runs-on: ubuntu-latest
        steps:
            - name: Deploting to Prod
              run: echo 'Deploying'
        